### ISSUE TITLE
Add a doc comment clarifying `Procedure::offset`

### ISSUE THREAD

**Issue by DrChat** [landaire/pdbview#5]
We got confused internally thinking it was an offset (from something) when it's actually an absolute address based on the preferred load address (right?) of the module.

**Comment by landaire** [comment]
Hmmmm I think you're right that a comment should be added for a point release, but I wonder if just changing it to be `address` in a new minor release would make sense. 

This field starts its life as an `offset`, and gets transformed here:

https://github.com/landaire/pdbview/blob/f69c19f44352ebb2c147a5250086a37a3cdf1c80/crates/ezpdb/src/symbol_types.rs#L613-L617C12

```
        let offset = address_map.and_then(|address_map| {
            offset
                .to_rva(address_map)
                .map(|rva| u32::from(rva) as usize + base_address)
        });
```

From the [`pdb` docs](https://docs.rs/pdb/latest/pdb/struct.PdbInternalSectionOffset.html):


> An offset relative to a PE section in the original unoptimized binary.
> 
> For optimized Microsoft binaries, this offset points to a virtual address space before the rearrangement of sections has been performed. This kind of offset is usually stored in PDB debug information. It can be converted to an RVA in the transformed address space of the optimized binary using [to_rva](https://docs.rs/pdb/latest/pdb/struct.PdbInternalSectionOffset.html#method.to_rva). Likewise, there is a conversion to [SectionOffset](https://docs.rs/pdb/latest/pdb/struct.SectionOffset.html) in the actual address space.
> 
> For binaries and their PDBs that have not been optimized, both address spaces are equal and the offsets are interchangeable. The conversion operations are cheap no-ops in this case.

I'm trying to remember why I call `to_rva()` to begin with -- probably because in the `pdbview` output it made more sense? Does transforming this to an RVA cause complications in your usage?

**Comment by DrChat** [comment]
Oh no there's no complications in our usage - in fact we prefer absolute addresses. Just got a little confused with the field's name.
Renaming it would probably work out better - I'm definitely not opposed.

**Comment by gabe-k** [comment]
@landaire so are u like gonna do anything or what

**Comment by landaire** [comment]
> @landaire so are u like gonna do anything or what

nerd https://github.com/landaire/pdbview/releases/tag/v0.6.0
